#!/bin/bash
# dev script version 1.1

HERE=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )/.." &> /dev/null && pwd )
NAME=metasmith
DEV_USER=hallamlab
_ver_file="$HERE/src/$NAME/version.txt"
_hash_file="$HERE/src/$NAME/build_hash.txt"
# version.txt holds the PEP 440 release segment (e.g. "0.18.2"). The build
# hash in build_hash.txt is regenerated by _build_hash.py at build time and
# identifies the exact source state. Together they form FULL_VER
# ("0.18.2+abc1234"); the docker tag is the same with '+' → '-'.
VER="$(cat $_ver_file)"
_compute_full_ver() {
    if [ -f "$_hash_file" ]; then
        echo "${VER}+$(cat $_hash_file)"
    else
        echo "${VER}"
    fi
}
FULL_VER="$(_compute_full_ver)"
DOCKER_TAG="${FULL_VER//+/-}"
DOCKER_IMAGE=quay.io/$DEV_USER/$NAME

# Refuse to publish or convert an image whose bundled relay binaries are
# stubs. Bug shipped in 0.18.4 where the Dockerfile happily COPYed 28-byte
# "#!/bin/sh\necho 'stub relay'" placeholders left over in main/relay_agent/
# target/ because the --update_container chain skips -br. Set
# MSM_SKIP_RELAY_CHECK=1 to override (e.g. emergency linux-only patch).
_assert_real_relays() {
    [ -n "$MSM_SKIP_RELAY_CHECK" ] && {
        echo "MSM_SKIP_RELAY_CHECK set — skipping relay binary check"
        return 0
    }
    local img="$DOCKER_IMAGE:$DOCKER_TAG"
    echo "checking relay binaries in $img"
    local out rc
    out=$(docker run --rm --entrypoint sh "$img" -c '
        bad=""
        for slot in x86_64-linux:7f454c46 arm64-linux:7f454c46 \
                    x86_64-darwin:cffaedfe arm64-darwin:cffaedfe; do
            tgt=${slot%:*}; want=${slot##*:}
            f=/app/msm_relay.$tgt
            sz=$(stat -c %s "$f" 2>/dev/null || echo 0)
            magic=$(head -c 4 "$f" 2>/dev/null | od -An -tx1 | tr -d " ")
            kind=stub
            case "$magic" in
                7f454c46) kind=ELF ;;
                cffaedfe|feedfacf) kind=Mach-O ;;
            esac
            ok=yes
            [ "$magic" = "$want" ] || ok=no
            [ "$sz" -gt 100000 ] || ok=no
            printf "  %-14s size=%-8s magic=%s  %s\n" "$tgt" "$sz" "$magic" "$kind"
            [ "$ok" = "yes" ] || bad="$bad $tgt"
        done
        [ -z "$bad" ] && exit 0
        echo "STUB:$bad"
        exit 1
    ' 2>&1)
    rc=$?
    echo "$out" | grep -v '^STUB:'
    if [ $rc -ne 0 ]; then
        local bad_slots
        bad_slots=$(echo "$out" | grep '^STUB:' | sed 's/^STUB://')
        echo ""
        echo "ERROR: stub relay binary detected in $img"
        echo "  bad slots:$bad_slots"
        echo ""
        echo "Rebuild relays first, then re-tag the image:"
        echo "  $HERE/dev/metasmith.sh -brc   # build the cross-compile container (one time)"
        echo "  $HERE/dev/metasmith.sh -br    # build all 4 relay targets"
        echo "  $HERE/dev/metasmith.sh -bd    # rebuild the docker image"
        echo ""
        echo "Override (NOT recommended) by setting MSM_SKIP_RELAY_CHECK=1."
        return 1
    fi
    return 0
}

# Refuse to publish or convert an image whose installed solver engine will not
# run. Same shape as the relay check above and for the same reason: the
# staging-directory guard (`_assert_solver_engine`) sees the files before pip
# touches them, and the failure this catches happens *during* packaging. A
# binary staged mode 444 -- which is how it arrived while `engine/` was
# DVC-tracked -- ships through the sdist as 444 and lands in the wheel as 644,
# so the guard at -bp passes and the image plans on the python fallback
# forever. Asking the installed package what it will actually use is the only
# check downstream of every mode-mangling step.
# Set MSM_SKIP_SOLVER_CHECK=1 to override (shared with the staging guard: they
# are the same claim, checked in two places).
_assert_engine_in_image() {
    [ -n "$MSM_SKIP_SOLVER_CHECK" ] && {
        echo "MSM_SKIP_SOLVER_CHECK set — skipping in-image solver engine check"
        return 0
    }
    local img="$DOCKER_IMAGE:$DOCKER_TAG"
    echo "checking solver engine in $img"
    local out rc
    out=$(docker run --rm --entrypoint sh "$img" -c '
        python - <<"PY"
import os, sys
from metasmith.models.solver_backend import Backend
from metasmith.models.solver_engine import packaged_engine_path, platform_slot
p = packaged_engine_path()
print(f"  slot={platform_slot()}")
print(f"  path={p}")
if p is not None:
    print(f"  mode={oct(os.stat(p).st_mode & 0o777)} exec={os.access(p, os.X_OK)}")
b = Backend("solve")
print(f"  backend={b}")
sys.exit(0 if b == "rust" else 1)
PY
    ' 2>&1)
    rc=$?
    echo "$out"
    if [ $rc -ne 0 ]; then
        echo ""
        echo "ERROR: the image at $img does not run the solver engine"
        echo "  It will plan on the python fallback -- correct, and roughly 15x slower."
        echo ""
        echo "  Rebuild the engine and the artifacts that carry it:"
        echo "    $HERE/dev/metasmith.sh -bec   # one time: pull the rust cross-compile container"
        echo "    $HERE/dev/metasmith.sh -be    # build all 4 targets and stage them"
        echo "    $HERE/dev/metasmith.sh -bp    # rebuild the sdist"
        echo "    $HERE/dev/metasmith.sh -bd    # rebuild the image"
        echo ""
        echo "  Override (NOT recommended) by setting MSM_SKIP_SOLVER_CHECK=1."
        return 1
    fi
    return 0
}

# The library half of the same idea, and the same reason: an image whose bundle
# is absent or empty installs, imports and runs. The only symptom is that the
# GUI's type panel is blank and no template is offered, which nobody sees until
# a user opens the page. Checked in the image because that is the artifact that
# ships, not the tree it was built from.
_assert_library_in_image() {
    [ -n "$MSM_SKIP_LIBRARY_CHECK" ] && {
        echo "MSM_SKIP_LIBRARY_CHECK set -- skipping in-image library check"
        return 0
    }
    local img="$DOCKER_IMAGE:$DOCKER_TAG"
    echo "checking standard library in $img"
    local out rc
    out=$(docker run --rm --entrypoint sh "$img" -c '
        python - <<"PY"
import sys
from metasmith.agents.templates import standard_library_root, library_index, TEMPLATES_DIR
root = standard_library_root()
print("  root=%s" % root)
if root is None:
    print("  no standard library in this image")
    sys.exit(1)
idx = library_index(root)
tdir = root/TEMPLATES_DIR
tpl = sorted(p.name for p in tdir.iterdir()) if tdir.is_dir() else []
print("  data_types=%d transforms=%d resources=%d templates=%d" % (
    len(idx["data_types"]), len(idx["transform_libraries"]),
    len(idx["resource_libraries"]), len(tpl)))
ok = bool(idx["data_types"]) and bool(idx["transform_libraries"]) and bool(tpl)
sys.exit(0 if ok else 1)
PY
    ' 2>&1)
    rc=$?
    echo "$out"
    if [ $rc -ne 0 ]; then
        echo ""
        echo "ERROR: the image at $img carries no usable standard library"
        echo "  metasmith will install, import and run; the GUI type panel will be"
        echo "  empty and no template will be offered."
        echo ""
        echo "    $HERE/dev/metasmith.sh --vendor-library   # stage it into the package"
        echo "    $HERE/dev/metasmith.sh -bp                # rebuild the sdist"
        echo "    $HERE/dev/metasmith.sh -bd                # rebuild the image"
        echo ""
        echo "  Override (NOT recommended) by setting MSM_SKIP_LIBRARY_CHECK=1."
        return 1
    fi
    return 0
}

# The conda half of the check above. conda-build is where the damage happens:
# with binary_relocation on it treats the cross-built ELFs as libraries of the
# build host, patchelfs them, and the x86_64-linux binary segfaults on exec.
# The recipe turns relocation off, so this asks the built package whether that
# is still true -- in a clean env, from a local channel, before the artifact
# leaves the machine. Nothing fails at build, install or import when it is not
# true; the planner just falls back to the python search.
# Set MSM_SKIP_SOLVER_CHECK=1 to override (shared with the two guards above:
# they are the same claim, checked in three places).
_assert_engine_in_conda_package() {
    [ -n "$MSM_SKIP_SOLVER_CHECK" ] && {
        echo "MSM_SKIP_SOLVER_CHECK set — skipping conda package solver engine check"
        return 0
    }
    local pkg
    pkg=$(find "$HERE/conda_build" -name "$NAME-*.tar.bz2" 2>/dev/null | head -1)
    if [ -z "$pkg" ]; then
        echo ""
        echo "ERROR: no built conda package under $HERE/conda_build"
        echo ""
        echo "  Build it first:"
        echo "    $HERE/dev/metasmith.sh -bc"
        echo ""
        echo "  Override (NOT recommended) by setting MSM_SKIP_SOLVER_CHECK=1."
        return 1
    fi
    local env_name="${NAME}_pkgcheck_$$"
    echo "installing $(basename "$pkg") into throwaway env [$env_name]"
    echo "  (a clean-room install; expect this to take a minute)"
    local out rc
    if ! out=$(env -u PYTHONPATH mamba create -y -n "$env_name" \
            -c "file://$HERE/conda_build" -c "$DEV_USER" -c bioconda -c conda-forge \
            "$NAME=$VER" 2>&1); then
        echo "$out" | tail -20
        echo ""
        echo "ERROR: the built conda package does not install into a clean env"
        echo "  Override (NOT recommended) by setting MSM_SKIP_SOLVER_CHECK=1."
        env -u PYTHONPATH mamba env remove -y -n "$env_name" >/dev/null 2>&1
        return 1
    fi
    # PYTHONPATH cleared throughout: the workspace checkout otherwise shadows
    # the install and this proves nothing.
    out=$(env -u PYTHONPATH mamba run -n "$env_name" python -c "
import os, sys
from metasmith.models.solver_backend import Backend
from metasmith.models.solver_engine import packaged_engine_path, platform_slot
p = packaged_engine_path()
print(f\"  slot={platform_slot()}\")
print(f\"  path={p}\")
if p is not None:
    print(f\"  mode={oct(os.stat(p).st_mode & 0o777)} exec={os.access(p, os.X_OK)}\")
b = Backend(\"solve\")
print(f\"  backend={b}\")
sys.exit(0 if b == \"rust\" else 1)
" 2>&1)
    rc=$?
    echo "$out"
    env -u PYTHONPATH mamba env remove -y -n "$env_name" >/dev/null 2>&1
    if [ $rc -ne 0 ]; then
        echo ""
        echo "ERROR: the conda package at $pkg does not run the solver engine"
        echo "  Published, it would plan on the python fallback -- correct, and"
        echo "  roughly 15x slower -- and nothing downstream would say so."
        echo ""
        echo "  Check binary_relocation/detect_binary_files_with_prefix are still"
        echo "  off in conda_recipe/metasmith/meta_template.yaml, then rebuild:"
        echo "    $HERE/dev/metasmith.sh -be    # build all 4 targets and stage them"
        echo "    $HERE/dev/metasmith.sh -bp    # rebuild the sdist"
        echo "    $HERE/dev/metasmith.sh -bc    # rebuild the conda package"
        echo ""
        echo "  Override (NOT recommended) by setting MSM_SKIP_SOLVER_CHECK=1."
        return 1
    fi
    return 0
}

# Refuse to bake a stale pip artifact into the image or conda package. dist/ is
# produced once by -bp and then frozen; -bd re-tags the image from the *live*
# source tree while installing whatever sdist sits in dist/, and -bc packages
# that same sdist. So an edit between -bp and -bd/-bc would ship an artifact
# whose embedded build hash disagrees with the image tag (and with the conda
# build). Recompute the live source hash and require a matching sdist in dist/.
# Override with MSM_SKIP_DIST_CHECK=1.
# Refuse to package without a built GUI bundle. It is generated rather than
# committed, so skipping --build-gui ships an empty static/ and `msm gui`
# serves nothing — a failure invisible until someone opens the page. Same
# shape as the stub-relay bug in 0.18.4, and guarded the same way. Set
# MSM_SKIP_GUI_CHECK=1 to override.
_gui_static="$HERE/src/$NAME/gui/static"
_assert_gui_bundle() {
    [ -n "$MSM_SKIP_GUI_CHECK" ] && {
        echo "MSM_SKIP_GUI_CHECK set — skipping GUI bundle check"
        return 0
    }
    if [ ! -f "$_gui_static/index.html" ]; then
        echo ""
        echo "ERROR: the GUI bundle is missing at $_gui_static"
        echo ""
        echo "  It is built, not committed, so a fresh checkout has none. Build it first:"
        echo "    $HERE/dev/metasmith.sh --build-gui"
        echo ""
        echo "  Override (NOT recommended) by setting MSM_SKIP_GUI_CHECK=1."
        return 1
    fi
    echo "gui bundle: $(du -sh "$_gui_static" | cut -f1) at $_gui_static"
    return 0
}

# Refuse to package a wheel whose solver binaries are missing, stubbed, or
# host-linked. Same failure shape as the stub relays and the unbuilt GUI bundle,
# and it is *quieter* than either: metasmith without a solver engine plans on
# the python fallback and works, just slowly, so nothing fails and no one finds
# out. The build-kind marker is written by the staging step because nothing
# about a linux ELF says whether it was linked against musl or against this
# machine's glibc, and only one of those runs on someone else's machine.
# Set MSM_SKIP_SOLVER_CHECK=1 to override.
_vendor_stage="$HERE/src/$NAME/vendor"
_lib_src="$HERE/src/metasmith_libraries"
_lib_envs="$HERE/envs/metasmith_libraries"
# The vendored standard library. Every failure here is silent at build, install
# and import time -- an empty bundle ships, metasmith runs, and the GUI's type
# panel is simply blank -- which is why it is a guard and not a comment. Same
# claim as the engine's, checked at the same three steps.
_assert_library_bundle() {
    [ -n "$MSM_SKIP_LIBRARY_CHECK" ] && {
        echo "MSM_SKIP_LIBRARY_CHECK set -- skipping library bundle check"
        return 0
    }
    if [ ! -f "$_vendor_stage/VENDOR_HASH" ]; then
        echo "no vendored standard library at [$_vendor_stage]"
        echo "  run: ./dev/metasmith.sh --vendor-library"
        return 1
    fi
    local missing=""
    for d in data_types transforms resources templates envs; do
        if [ ! -d "$_vendor_stage/$d" ] || [ -z "$(ls -A "$_vendor_stage/$d" 2>/dev/null)" ]; then
            missing="$missing $d"
        fi
    done
    if [ -n "$missing" ]; then
        echo "vendored library at [$_vendor_stage] is missing or empty:$missing"
        echo "  run: ./dev/metasmith.sh --vendor-library"
        return 1
    fi
    local ntpl
    ntpl=$(ls -1 "$_vendor_stage/templates" 2>/dev/null | wc -l)
    echo "vendored library ok: $(cat "$_vendor_stage/VENDOR_HASH"), $ntpl templates"
    return 0
}

_engine_stage="$HERE/src/$NAME/engine"
_assert_solver_engine() {
    [ -n "$MSM_SKIP_SOLVER_CHECK" ] && {
        echo "MSM_SKIP_SOLVER_CHECK set — skipping solver engine check"
        return 0
    }
    local bad="" kind="(none)"
    [ -f "$_engine_stage/BUILD_KIND" ] && kind="$(cat "$_engine_stage/BUILD_KIND")"
    for slot in x86_64-linux:7f454c46 arm64-linux:7f454c46 \
                x86_64-darwin:cffaedfe arm64-darwin:cffaedfe; do
        local tgt=${slot%:*} want=${slot##*:}
        local f="$_engine_stage/msm_solver.$tgt"
        local sz magic mode ok=yes
        sz=$(stat -c %s "$f" 2>/dev/null || echo 0)
        magic=$(head -c 4 "$f" 2>/dev/null | od -An -tx1 | tr -d " ")
        mode=$(stat -c %a "$f" 2>/dev/null || echo "---")
        [ "$magic" = "$want" ] || ok=no
        [ "$sz" -gt 100000 ] || ok=no
        # The exec bit. It is the one way these fail that leaves a perfectly
        # valid binary in place: DVC-tracking this directory checked it out
        # mode 444, so every plan in every worktree hit a permission error at
        # the handshake and silently reverted to the python solver. The mode
        # follows the file into the artifacts too -- 444 survives an sdist and
        # normalises to 644 in the wheel, neither of which runs.
        [ -x "$f" ] || ok=no
        printf "  %-14s size=%-8s magic=%-8s mode=%-4s %s\n" "$tgt" "$sz" "${magic:-none}" "$mode" "$ok"
        [ "$ok" = "yes" ] || bad="$bad $tgt"
    done
    if [ -n "$bad" ] || [ "$kind" != "cross" ]; then
        echo ""
        echo "ERROR: the solver engine binaries in $_engine_stage are not shippable"
        [ -n "$bad" ] && echo "  bad or missing slots:$bad"
        [ "$kind" != "cross" ] && echo "  build kind is [$kind], expected [cross] (a -bl build only runs on this host)"
        echo ""
        echo "  Build them first:"
        echo "    $HERE/dev/metasmith.sh -bec   # one time: pull the rust cross-compile container"
        echo "    $HERE/dev/metasmith.sh -be    # build all 4 targets and stage them"
        echo ""
        echo "  Without them metasmith still plans, on the python solver — which is"
        echo "  why this is a guard rather than a build failure you'd notice."
        echo "  Override (NOT recommended) by setting MSM_SKIP_SOLVER_CHECK=1."
        return 1
    fi
    echo "solver engine: 4/4 cross-built binaries in $_engine_stage"
    return 0
}

_assert_dist_matches_source() {
    [ -n "$MSM_SKIP_DIST_CHECK" ] && {
        echo "MSM_SKIP_DIST_CHECK set — skipping dist/source hash check"
        return 0
    }
    local live_hash live_full want
    live_hash=$(PYTHONPATH="$HERE/src" python -m metasmith._build_hash 2>/dev/null)
    if [ -z "$live_hash" ]; then
        echo "ERROR: could not compute the source build hash (is the metasmith env active?)"
        return 1
    fi
    live_full="${VER}+${live_hash}"
    want="$HERE/dist/$NAME-$live_full.tar.gz"
    if [ ! -f "$want" ]; then
        echo ""
        echo "ERROR: dist/ does not match the current source tree (build hash drift)."
        echo "  expected sdist: dist/$NAME-$live_full.tar.gz"
        echo "  live source hash: $live_hash   (version $VER)"
        echo "  present in dist/:"
        ( ls -1 "$HERE"/dist/*.tar.gz 2>/dev/null || echo "    (no sdist present)" ) | sed 's#.*/#    #'
        echo ""
        echo "  The pip artifacts are stale relative to the source, so the image would be"
        echo "  tagged with a hash that does not match the code baked into it. Rebuild:"
        echo "    $HERE/dev/metasmith.sh -bp"
        echo ""
        echo "  Override (NOT recommended) by setting MSM_SKIP_DIST_CHECK=1."
        return 1
    fi
    echo "dist/ matches source: $NAME-$live_full.tar.gz"
    return 0
}

# CONDA=conda
CONDA=mamba # https://mamba.readthedocs.io/en/latest/mamba-installation.html#mamba-install
echo image: $DOCKER_IMAGE:$DOCKER_TAG
echo ""

# this file contains a list of commands useful for dev,
# providing automation for some build tasks
#
# example workflow 1, pip:
# dev.sh --idev # create a local conda dev env
# # add pypi api token as file to ./secrets [https://pypi.org/help/#apitoken]
# # make some changes to source
# # bump up ./src/*/version.txt
# dev.sh --build-gui # build the frontend bundle (needs node; not committed)
# dev.sh -bp # build the pip package
# dev.sh -up # test upload to testpypi
# dev.sh -upload-pypi # release to pypi index for pip install
#
# example workflow 2, conda:
# dev.sh --idev # create a local conda dev env
# dev.sh -bp # build the pip package
# dev.sh -bc # build conda package from pip package
# dev.sh -uc # publish to conda index
#
# example workflow 3, containerization:
# dev.sh --idev # create a local conda dev env
# dev.sh --build-gui # build the frontend bundle (needs node; not committed)
# dev.sh -bd # build docker image
# dev.sh -ud # publish to quay.io
# dev.sh -bs # build apptainer image from local docker image

case $1 in
    ###################################################
    # environments

    --idev) # with dev tools for packaging
        cd $HERE/envs/metasmith
        echo "updating conda env: $2"
        echo "WARNING: you will need to install docker and apptainer individually"
        sleep 2
        $CONDA env update -n $2 -f ./dev.yml
    ;;
    --ibase) # base only
        cd $HERE/envs/metasmith
        echo "creating new conda env: $NAME"
        sleep 2
        $CONDA env create --no-default-packages -n $NAME -f ./base.yml
    ;;
    --git-prune-local) # remove local branches not on remote
        git fetch -p
        git branch -r \
            | awk '{print $1}' \
            | egrep -v -f /dev/fd/0 <(git branch -vv \
            | grep origin) \
            | awk '{print $1}' \
            | xargs git branch -d
    ;;

    ###################################################
    # build
    --vendor-library) # stage the standard library into the package so it ships
        # Content only -- no _metadata/. The consumer compiles its own copy in a
        # writable place (`gui.stdlib.clone_stdlib`), so shipping a compiled
        # index would ship a build product that is discarded on arrival. That is
        # also what removes the ordering hazard this step used to carry: nothing
        # here needs a compiled library, so nothing has to be compiled first.
        PYTHONPATH="$HERE/src" python -m $NAME build vendor-library --no-metadata \
            --src "data_types=$_lib_src/data_types" \
            --src "transforms=$_lib_src/transforms" \
            --src "resources=$_lib_src/resources" \
            --src "templates=$_lib_src/templates" \
            --src "envs=$_lib_envs" \
            --dst "$_vendor_stage" || exit 1
    ;;
    --build-gui) # frontend bundle for `msm gui`
        # Needs node. It is a build dependency only — the bundle is shipped
        # prebuilt, so the runtime env has no use for it and base.yml does not
        # carry it.
        command -v npm >/dev/null || {
            echo "ERROR: npm not found. The GUI bundle needs node to build:"
            echo "  conda create -n msm_node -c conda-forge nodejs"
            echo "  conda activate msm_node && $HERE/dev/metasmith.sh --build-gui"
            exit 1
        }
        cd $HERE/src/metasmith/frontend
        [ -d node_modules ] || npm install --no-audit --no-fund
        npm run build
    ;;
    -bp) # pip
        # build pip package
        _assert_gui_bundle || exit 1
        _assert_solver_engine || exit 1
        _assert_library_bundle || exit 1
        [ -d ./build ] && rm -r build
        [ -d ./dist ] && rm -r dist
        # Stamp build_hash.txt before sdist/wheel so FULL_VERSION is baked in.
        PYTHONPATH="$HERE/src" python -m metasmith._build_hash --write >/dev/null
        FULL_VER="$(_compute_full_ver)"
        DOCKER_TAG="${FULL_VER//+/-}"
        echo "build hash: $(cat $_hash_file)"
        echo "full version: $FULL_VER"
        python -m build
    ;;
    -bpi) # pip - test install
        pip install $HERE/dist/$NAME-$FULL_VER-py3-none-any.whl --force-reinstall
    ;;
    -bpx) # pip - remove package
        pip uninstall -y $NAME
    ;;
    -bc) # conda
        # requires built pip package
        _assert_solver_engine || exit 1
        _assert_library_bundle || exit 1
        _assert_dist_matches_source || exit 1
        rm -r $HERE/conda_build
        python ./conda_recipe/metasmith/compile_recipe.py
        $HERE/conda_recipe/metasmith/call_build.sh
    ;;
    -brc) # build the container for building the relay
        cd $HERE/src/bash_relay
        ./dev.sh -bb
    ;;
    -br) # build the relay
        cd $HERE/src/bash_relay
        ./dev.sh -b
    ;;
    -bec) # build the container for building the solver engine
        # The same upstream image the relay uses, so -brc and this are
        # interchangeable; both exist so neither build has to know about the other.
        cd $HERE/src/workflow_solver
        ./dev.sh -bb
    ;;
    -be) # build the solver engine (4 targets) and stage it into the package
        cd $HERE/src/workflow_solver
        ./dev.sh -b
    ;;
    -bel) # solver engine, host toolchain, host target only — dev loop, not shippable
        cd $HERE/src/workflow_solver
        ./dev.sh -bl
    ;;
    -bd) # docker
        _assert_gui_bundle || exit 1
        _assert_library_bundle || exit 1
        # The image installs the sdist, so it carries whatever is staged here.
        # A stale stage is *mostly* self-detecting -- engine/ sits inside the
        # tree _build_hash walks, so staging changes FULL_VERSION -- but that
        # reports a hash mismatch rather than naming the cause.
        _assert_solver_engine || exit 1
        # pre-download requirements
        mkdir -p $HERE/lib
        cd $HERE/lib
        TINI_VERSION=v0.19.0
        ! [ -f tini ] && wget https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini && chmod +x ./tini
        if ! [ -d globusconnectpersonal-latest ]; then
            wget -continue https://downloads.globus.org/globus-connect-personal/linux/stable/globusconnectpersonal-latest.tgz
            tar -xvf globusconnectpersonal-latest.tgz
            rm globusconnectpersonal-latest.tgz
            mv globusconnectpersonal-* globusconnectpersonal-latest
        fi
        NEXTFLOW_VERSION=$(cat ../envs/metasmith/base.yml | grep nextflow | cut -c14- | xargs)
        echo "nextflow version: $NEXTFLOW_VERSION"
        ! [ -f nextflow ] && wget https://github.com/nextflow-io/nextflow/releases/download/v${NEXTFLOW_VERSION}/nextflow && chmod +x ./nextflow
        cd $HERE

        # Stamp build_hash.txt so the image we tag matches FULL_VERSION exactly.
        PYTHONPATH="$HERE/src" python -m metasmith._build_hash --write >/dev/null
        FULL_VER="$(_compute_full_ver)"
        DOCKER_TAG="${FULL_VER//+/-}"
        echo image: $DOCKER_IMAGE:$DOCKER_TAG

        # the sdist the Dockerfile installs must match the tag we just computed,
        # else the image's contents and its tag (and the conda build) disagree
        _assert_dist_matches_source || exit 1

        # build the docker container locally
        export DOCKER_BUILDKIT=1
        # --network=host because I ran into a network error
        docker build \
            -f $HERE/docker/metasmith/Dockerfile \
            --build-arg="CONDA_ENV=${NAME}_env" \
            --build-arg="PACKAGE=${NAME}" \
            --build-arg="VERSION=${FULL_VER}" \
            --network=host \
            -t $DOCKER_IMAGE:$DOCKER_TAG $HERE \
        && docker inspect --format='{{.Size}}' $DOCKER_IMAGE:$DOCKER_TAG | numfmt --to=si
    ;;
    -bs) # apptainer image *from docker*
        _assert_real_relays || exit 1
        _assert_engine_in_image || exit 1
        _assert_library_in_image || exit 1
        apptainer build --force $NAME.sif docker-daemon://$DOCKER_IMAGE:$DOCKER_TAG
    ;;
    --update_container)
        $HERE/dev/metasmith.sh -bp && $HERE/dev/metasmith.sh -bd && $HERE/dev/metasmith.sh -ud && $HERE/dev/metasmith.sh -bs
    ;;
    --update_conda)
        $HERE/dev/metasmith.sh -bc && $HERE/dev/metasmith.sh -uc
    ;;
    ###################################################
    # upload

    -up) # pip (testpypi)
        PYPI=testpypi
        TOKEN=$(cat secrets/${PYPI}) # https://pypi.org/help/#apitoken
        python -m twine upload --repository $PYPI dist/*.whl -u __token__ -p $TOKEN
    ;;
    -upload-pypi) # pip (pypi)
        echo "not all dependencies are available on pypi, so this is not a good idea..."
        # PYPI=pypi
        # TOKEN=$(cat secrets/${PYPI}) # https://pypi.org/help/#apitoken
        # python -m twine upload --repository $PYPI dist/*.whl -u __token__ -p $TOKEN
    ;;
    -uc) # conda (personal channel)
        # run `anaconda login` first
        _assert_engine_in_conda_package || exit 1
        find ./conda_build -name *.tar.bz2 | xargs -I % anaconda upload -u $DEV_USER %
    ;;
    -ud) # docker
        # login and push image to quay.io
        # sudo docker login quay.io
        _assert_real_relays || exit 1
        _assert_engine_in_image || exit 1
        _assert_library_in_image || exit 1
	    docker push $DOCKER_IMAGE:$DOCKER_TAG
        # `latest` and the bare version are what a user without a pinned tag
        # gets, so they move with the push rather than in a later web-UI visit.
        for alias in latest "$VER"; do
            docker tag $DOCKER_IMAGE:$DOCKER_TAG $DOCKER_IMAGE:$alias
            docker push $DOCKER_IMAGE:$alias
        done
        echo "https://$DOCKER_IMAGE?tab=tags"
    ;;

    ###################################################
    # run

    -r)
        shift
        # This also settles where the solver engine comes from: putting src/ on
        # the path makes src/metasmith/engine/ the package's own engine dir --
        # the exact directory an installed wheel resolves against, and the one
        # -be/-bel stage into. So there is one lookup in all three contexts and
        # nothing to add to PATH. Run -bel once and source runs use the engine.
        export PYTHONPATH=$HERE/src:$PYTHONPATH
        python -m $NAME $@
    ;;
    --gui) # serve the web GUI over its own scratch workspace
        shift
        # Pinned, not prepended, for the same reason -tg pins it: a workspace
        # PYTHONPATH resolves `metasmith` to some *other* checkout, and the
        # page then serves a server none of your edits are in -- which reads
        # as "my change did nothing" rather than as a wrong interpreter.
        export PYTHONPATH=$HERE/src
        # `msm gui` writes its project directory (agents/, workflows/, runs/,
        # the served config, the standard-library clone) into the cwd, so it
        # is given one under scratch/ -- already gitignored wholesale -- and
        # never the repo root, which it would otherwise litter.
        ws=$HERE/src/metasmith/scratch/gui-main
        mkdir -p $ws
        cd $ws
        python -m $NAME gui $@
    ;;
    -rd) # docker
            # -e XDG_CACHE_HOME="/ws"\
        shift
        mkdir -p $HERE/src/metasmith/scratch/docker
        cd $HERE/src/metasmith/scratch/docker
        # mkdir -p cache/.globus cache/.globusonline
        docker run -it --rm \
            -u $(id -u):$(id -g) \
            --mount type=bind,source="/tmp",target="/tmp"\
            --mount type=bind,source="$HERE/src/metasmith/scratch/docker",target="/ws"\
            --mount type=bind,source="$HOME/.globus",target="/.globus"\
            --mount type=bind,source="$HOME/.globusonline",target="/.globusonline"\
            --workdir="/ws" \
            $DOCKER_IMAGE:$DOCKER_TAG /bin/bash
    ;;
    -rs) # apptainer
            # -e XDG_CACHE_HOME="/ws"\
        shift
        mkdir -p $HERE/src/metasmith/scratch/docker
        cd $HERE/src/metasmith/scratch/docker
        apptainer exec \
            --bind ./:/ws \
            --workdir /ws \
            --no-home \
            $HERE/$NAME.sif /bin/bash
            # docker-daemon://$DOCKER_IMAGE:$DOCKER_TAG /bin/bash
    ;;

    ###################################################
    # test

    -t)
        shift
        export PYTHONPATH=$HERE/src:$PYTHONPATH
        ws=$HERE/src/metasmith/scratch/test_ws
        mkdir -p $ws
        cd $ws
        python -m $NAME lab $@
    ;;

    -tt)
        shift
        cd $HERE
        export PYTHONPATH=$HERE/src:$PYTHONPATH
        pytest $@
    ;;

    -tg) # just the GUI's suite -- the inner loop while working on the page
        shift
        cd $HERE
        # Pinned, not prepended: a *relative* entry inherited from the caller's
        # PYTHONPATH (a workspace that exports `../../src`) is re-resolved
        # against the cwd of every process and every temp dir a test chdirs to,
        # and the stat misses alone doubled this suite's wall time.
        export PYTHONPATH=$HERE/src
        # The directory is the definition of the set -- tests/conftest.py stamps
        # `gui` on everything under it, and a file that lands under no axis at
        # all fails collection rather than going quiet. Handing pytest the path
        # matters as much as the -m: collection imports every module it walks,
        # and importing the e2e ones costs more than this whole suite takes.
        [ -d "$HERE/tests/metasmith/gui" ] || { echo "tests/metasmith/gui/ is missing"; exit 1; }
        # -q and no per-test names: this is meant to be run every minute, so
        # what it prints is the count and the failures, not a 200-line roster.
        pytest -m gui -q --durations=0 --durations-min=0.25 $HERE/tests/metasmith/gui $@
    ;;

    -tl) # the process-lifecycle suite -- what actually dies when a run is stopped
        shift
        cd $HERE
        # Pinned, not prepended -- same reason as -tg.
        export PYTHONPATH=$HERE/src
        # The directory is the definition of the set, and handing pytest the
        # path keeps collection from importing the e2e modules.
        [ -d "$HERE/tests/metasmith/lifecycle" ] || { echo "tests/metasmith/lifecycle/ is missing"; exit 1; }
        # These spawn real process trees, so a hang here is a hang with children:
        # --durations makes a test that is waiting out a kill ladder obvious.
        pytest -m lifecycle -q --durations=0 --durations-min=1.0 $HERE/tests/metasmith/lifecycle $@
    ;;

    -td) # inject updates to an agent home for dev binds
        shift
        export PYTHONPATH=$HERE/src:$HERE/src/metasmith/lib:$PYTHONPATH
        python3 research/metasmith/local_mock/rsync.py $@
    ;;

    -t2)
        cd $HERE/src/bash_relay/scratch/cache/mock
        # mkdir -p cache/.globus cache/.globusonline
        docker run -it --rm \
            -u $(id -u):$(id -g) \
            -e NXF_HOME="/ws/.nextflow" \
            --mount type=bind,source="$HERE/research/metasmith/local_mock/cache/local_home/runs/dwfuH8Cz",target="/ws"\
            --mount type=bind,source="$HERE/research/metasmith/local_mock/cache/local_home",target="/msm_home"\
            --mount type=bind,source="$HOME/.globus",target="/.globus"\
            --mount type=bind,source="$HOME/.globusonline",target="/.globusonline"\
            --workdir="/ws" \
            $DOCKER_IMAGE:$DOCKER_TAG /bin/bash
    ;;

    ###################################################
    # docs

    --docs) # build docs
        shift
        cd $HERE/docs/metasmith
        sphinx-autobuild -a ./source ./build/html
    ;;

    ###################################################

    *)
        echo "bad option"
        echo $1
    ;;
esac
