# generated by transforms/aspire/_generate.py -- do not hand-edit
"""asv_mag_network -- ASV_MAG_NETWORK (asv_pipeline.nf:5654)

the .nf picks the unthresholded or thresholded graph by config
(`asv_mag_network.graph_variant`). Ported against the unthresholded one; a
variant switch would be a seventh token for something no consumer can tell
apart.

Stub: the model is the port, the body only touches its outputs.
Regenerate with `python transforms/aspire/_generate.py`.
"""

from metasmith.python_api import *

lib   = TransformInstanceLibrary.ResolveParentLibrary(__file__)
model = Transform()
run     = model.AddRequirement(lib.GetType("aspire::run"))
graph   = model.AddRequirement(lib.GetType("aspire::network_graph_all"), parents={run})
nf      = model.AddRequirement(lib.GetType("aspire::network_node_features"), parents={run})
tax     = model.AddRequirement(lib.GetType("amplicon::asv_taxonomy"), parents={run})
counts  = model.AddRequirement(lib.GetType("aspire::analysis_counts"), parents={run})
pairing = model.AddRequirement(lib.GetType("aspire::asv_mag_pairing"), parents={run})
magl    = model.AddRequirement(lib.GetType("aspire::asv_mag_outputs"), parents={run})
out     = model.AddProduct(lib.GetType("aspire::asv_mag_network_outputs"))

def protocol(context: ExecutionContext):
    made = {
        out: context.Output(out),
    }
    for key, path in made.items():
        make = 'mkdir -p' if key in _DIRECTORY_PRODUCTS else 'touch'
        context.external_shell.Exec(f'{make} {path.external}')
    return ExecutionResult(
        manifest=[{k: v.local for k, v in made.items()}],
        success=all(v.local.exists() for v in made.values()),
    )

_DIRECTORY_PRODUCTS = {out}

TransformInstance(
    protocol=protocol,
    model=model,
    group_by=run,
    resources=Resources(
        cpus=4,
        memory=Size.GB(16),
        duration=Duration(hours=4),
    ),
)
