# generated by transforms/aspire/_generate.py -- do not hand-edit
"""asv_mag_link_absent -- no .nf process

r4 ecology lift (second pass): lifted off the study root onto the generic
`amplicon::survey` grouping node so `spieceasi` and `graph_network` -- lifted
in the first pass -- are actually REACHABLE from a bare `amplicon::asv_table`.
Lifting a transform whose own inputs are still gated moves the gate, it does
not remove it. See research/kbase/curation/r4/analyses.md. Only the OFF arm
lifts. `asv_mag_link` itself reads `aspire::asv_filtered_seqs`, which no
transform outside the ASPIRE lane produces, so linking ASVs to MAGs stays a
pipeline capability while declining to link them does not.

Stub: the model is the port, the body only touches its outputs.
Regenerate with `python transforms/aspire/_generate.py`.
"""

from metasmith.python_api import *

lib   = TransformInstanceLibrary.ResolveParentLibrary(__file__)
model = Transform()
survey  = model.AddRequirement(lib.GetType("amplicon::survey"))
policy  = model.AddRequirement(lib.GetType("aspire::asv_mag_link_off"), parents={survey})
pairing = model.AddProduct(lib.GetType("aspire::asv_mag_pairing"))
out     = model.AddProduct(lib.GetType("aspire::asv_mag_outputs"))

def protocol(context: ExecutionContext):
    made = {
        pairing: context.Output(pairing),
        out: context.Output(out),
    }
    for key, path in made.items():
        make = 'mkdir -p' if key in _DIRECTORY_PRODUCTS else 'touch'
        context.external_shell.Exec(f'{make} {path.external}')
    return ExecutionResult(
        manifest=[{k: v.local for k, v in made.items()}],
        success=all(v.local.exists() for v in made.values()),
    )

_DIRECTORY_PRODUCTS = {out}

TransformInstance(
    protocol=protocol,
    model=model,
    group_by=survey,
    resources=Resources(
        cpus=1,
        memory=Size.GB(4),
        duration=Duration(hours=1),
    ),
)
