# generated by transforms/aspire/_generate.py -- do not hand-edit
"""asv_mag_link -- ASV_MAG_LINK (asv_pipeline.nf:5821)

`asv_mag_link.done` stood for two different things at its four consumers: the
pairing table the network stages read by path, and the results directory the
master summary scans. Both are declared. The .nf read the genomes from
`--genome-qc-dir`; that layout is `aspire::mag_collection`.

Stub: the model is the port, the body only touches its outputs.
Regenerate with `python transforms/aspire/_generate.py`.
"""

from metasmith.python_api import *

lib   = TransformInstanceLibrary.ResolveParentLibrary(__file__)
model = Transform()
study   = model.AddRequirement(lib.GetType("aspire::study_metadata"))
policy  = model.AddRequirement(lib.GetType("aspire::asv_mag_link_on"), parents={study})
fseqs   = model.AddRequirement(lib.GetType("aspire::asv_filtered_seqs"), parents={study})
mags    = model.AddRequirement(lib.GetType("aspire::mag_collection"))
pairing = model.AddProduct(lib.GetType("aspire::asv_mag_pairing"))
out     = model.AddProduct(lib.GetType("aspire::asv_mag_outputs"))

def protocol(context: ExecutionContext):
    made = {
        pairing: context.Output(pairing),
        out: context.Output(out),
    }
    for key, path in made.items():
        make = 'mkdir -p' if key in _DIRECTORY_PRODUCTS else 'touch'
        context.external_shell.Exec(f'{make} {path.external}')
    return ExecutionResult(
        manifest=[{k: v.local for k, v in made.items()}],
        success=all(v.local.exists() for v in made.values()),
    )

_DIRECTORY_PRODUCTS = {out}

TransformInstance(
    protocol=protocol,
    model=model,
    group_by=study,
    resources=Resources(
        cpus=8,
        memory=Size.GB(32),
        duration=Duration(hours=8),
    ),
)
