# generated by transforms/aspire/_generate.py -- do not hand-edit
"""clustermaps -- CLUSTERMAPS (asv_pipeline.nf:5324)

the .nf passes a boolean saying whether indicator species ran and then globs
the tables out of a shared directory. The directory is the real edge, so it is
what is declared.

Stub: the model is the port, the body only touches its outputs.
Regenerate with `python transforms/aspire/_generate.py`.
"""

from metasmith.python_api import *

lib   = TransformInstanceLibrary.ResolveParentLibrary(__file__)
model = Transform()
run    = model.AddRequirement(lib.GetType("aspire::run"))
am     = model.AddRequirement(lib.GetType("aspire::analysis_asv_meta"), parents={run})
md     = model.AddRequirement(lib.GetType("aspire::analysis_metadata"), parents={run})
tables = model.AddRequirement(lib.GetType("aspire::indicspecies_tables"), parents={run})
mito   = model.AddRequirement(lib.GetType("aspire::counts_mito"), parents={run})
out    = model.AddProduct(lib.GetType("aspire::clustermap_outputs"))

def protocol(context: ExecutionContext):
    made = {
        out: context.Output(out),
    }
    for key, path in made.items():
        make = 'mkdir -p' if key in _DIRECTORY_PRODUCTS else 'touch'
        context.external_shell.Exec(f'{make} {path.external}')
    return ExecutionResult(
        manifest=[{k: v.local for k, v in made.items()}],
        success=all(v.local.exists() for v in made.values()),
    )

_DIRECTORY_PRODUCTS = {out}

TransformInstance(
    protocol=protocol,
    model=model,
    group_by=run,
    resources=Resources(
        cpus=4,
        memory=Size.GB(16),
        duration=Duration(hours=3),
    ),
)
