# generated by transforms/aspire/_generate.py -- do not hand-edit
"""curate -- MITO_DECONTAM (asv_pipeline.nf:3595)

Folded in: FILTER_COUNTS (asv_pipeline.nf:3637)

Decides every non-target call and applies it in one step. The .nf split this
in two and partitioned the result into four count tables; here there are two,
the counts kept and the counts removed, and each removed ASV carries its
reason (mitochondrial, contaminant, below abundance, taxonomy). Thresholds
under `curate:`. Negative controls are not modelled yet; they belong here as a
second evidence input beside the contaminant hits.

Stub: the model is the port, the body only touches its outputs.
Regenerate with `python transforms/aspire/_generate.py`.
"""

from metasmith.python_api import *

lib   = TransformInstanceLibrary.ResolveParentLibrary(__file__)
model = Transform()
run       = model.AddRequirement(lib.GetType("aspire::run"))
fcounts   = model.AddRequirement(lib.GetType("aspire::asv_filtered_counts"), parents={run})
fseqs     = model.AddRequirement(lib.GetType("aspire::asv_filtered_seqs"), parents={run})
tax       = model.AddRequirement(lib.GetType("amplicon::asv_taxonomy"), parents={run})
master    = model.AddRequirement(lib.GetType("aspire::mitomaster_table"), parents={run})
mhits     = model.AddRequirement(lib.GetType("aspire::mito_blast6"), parents={run})
chits     = model.AddRequirement(lib.GetType("aspire::contaminant_blast6"), parents={run})
params    = model.AddRequirement(lib.GetType("aspire::params"), parents={run})
clean     = model.AddProduct(lib.GetType("aspire::counts_clean"))
removed   = model.AddProduct(lib.GetType("aspire::counts_removed"))
summaries = model.AddProduct(lib.GetType("aspire::mito_summary_tables"))
plots     = model.AddProduct(lib.GetType("aspire::mito_plots"))

def protocol(context: ExecutionContext):
    made = {
        clean: context.Output(clean),
        removed: context.Output(removed),
        summaries: context.Output(summaries),
        plots: context.Output(plots),
    }
    for key, path in made.items():
        make = 'mkdir -p' if key in _DIRECTORY_PRODUCTS else 'touch'
        context.external_shell.Exec(f'{make} {path.external}')
    return ExecutionResult(
        manifest=[{k: v.local for k, v in made.items()}],
        success=all(v.local.exists() for v in made.values()),
    )

_DIRECTORY_PRODUCTS = {summaries, plots}

TransformInstance(
    protocol=protocol,
    model=model,
    group_by=run,
    resources=Resources(
        cpus=1,
        memory=Size.GB(4),
        duration=Duration(hours=1),
    ),
)
