# generated by transforms/aspire/_generate.py -- do not hand-edit
"""denoise -- DENOISE (asv_pipeline.nf:3367)

Folded in: RELABEL_FILTERED (asv_pipeline.nf:3248), CONCAT_FASTAS
(asv_pipeline.nf:3274), DEREPLICATE (asv_pipeline.nf:3298), CHIMERA_CHECK
(asv_pipeline.nf:3393), CREATE_COUNT_MATRIX (asv_pipeline.nf:3417)

The study fan-in, and the one place reads become ASVs. Relabel each sample's
headers from the `sample` key of the read_metadata its fasta descends from
(context.SourceOf, never the position in the group), concatenate,
`--derep_fulllength`, `--cluster_unoise` (under `unoise:`),
`--uchime3_denovo`, then `--usearch_global` of the pooled reads against the
non-chimeric centroids (under `count:`). Every intermediate had exactly one
consumer. The two products are the library's generic ASV types, so this is the
seam a long-read denoiser joins at, the way both read lengths meet at
`sequences::assembly`.

Stub: the model is the port, the body only touches its outputs.
Regenerate with `python transforms/aspire/_generate.py`.
"""

from metasmith.python_api import *

lib   = TransformInstanceLibrary.ResolveParentLibrary(__file__)
model = Transform()
study    = model.AddRequirement(lib.GetType("aspire::study_metadata"))
meta     = model.AddRequirement(lib.GetType("sequences::read_metadata"), parents={study})
filtered = model.AddRequirement(lib.GetType("aspire::filtered_fasta"), parents={meta})
params   = model.AddRequirement(lib.GetType("aspire::params"), parents={study})
counts   = model.AddProduct(lib.GetType("amplicon::asv_table"))
seqs     = model.AddProduct(lib.GetType("amplicon::asv_seqs"))

def protocol(context: ExecutionContext):
    made = {
        counts: context.Output(counts),
        seqs: context.Output(seqs),
    }
    for key, path in made.items():
        make = 'mkdir -p' if key in _DIRECTORY_PRODUCTS else 'touch'
        context.external_shell.Exec(f'{make} {path.external}')
    return ExecutionResult(
        manifest=[{k: v.local for k, v in made.items()}],
        success=all(v.local.exists() for v in made.values()),
    )

_DIRECTORY_PRODUCTS = set()

TransformInstance(
    protocol=protocol,
    model=model,
    group_by=study,
    resources=Resources(
        cpus=8,
        memory=Size.GB(16),
        duration=Duration(hours=6),
    ),
)
