# generated by transforms/aspire/_generate.py -- do not hand-edit
"""diversity_mito -- DIVERSITY_ANALYSIS (asv_pipeline.nf:4399)

Groups are the label columns of the sample sheet; the analysis runs once per
label and skips a label with fewer than two levels. The .nf's
`diversity.run_mito` branch, split out so the generic row stays reachable from
any count table. The mitochondrial counts are the removed counts whose reason
is mitochondrial, laid out as upstream's ASV_target.mito.tsv.

Stub: the model is the port, the body only touches its outputs.
Regenerate with `python transforms/aspire/_generate.py`.
"""

from metasmith.python_api import *

lib   = TransformInstanceLibrary.ResolveParentLibrary(__file__)
model = Transform()
study   = model.AddRequirement(lib.GetType("aspire::study_metadata"))
counts  = model.AddRequirement(lib.GetType("aspire::analysis_counts"), parents={study})
removed = model.AddRequirement(lib.GetType("aspire::counts_removed"), parents={study})
md      = model.AddRequirement(lib.GetType("aspire::analysis_metadata"), parents={study})
out     = model.AddProduct(lib.GetType("aspire::diversity_mito_outputs"))

def protocol(context: ExecutionContext):
    made = {
        out: context.Output(out),
    }
    for key, path in made.items():
        make = 'mkdir -p' if key in _DIRECTORY_PRODUCTS else 'touch'
        context.external_shell.Exec(f'{make} {path.external}')
    return ExecutionResult(
        manifest=[{k: v.local for k, v in made.items()}],
        success=all(v.local.exists() for v in made.values()),
    )

_DIRECTORY_PRODUCTS = {out}

TransformInstance(
    protocol=protocol,
    model=model,
    group_by=study,
    resources=Resources(
        cpus=4,
        memory=Size.GB(16),
        duration=Duration(hours=3),
    ),
)
