# generated by transforms/aspire/_generate.py -- do not hand-edit
"""diversity_analysis -- DIVERSITY_ANALYSIS (asv_pipeline.nf:4399)

Groups are the label columns of the sample sheet; the analysis runs once per
label and skips a label with fewer than two levels. r4 ecology lift: requires
the generic `amplicon::survey` grouping node and a bare `amplicon::asv_table`
instead of the study root and `aspire::analysis_counts`, so it is reachable
from any count table -- `kbase/profile_abundance/kraken_abundance.py` produces
one from kraken2 reports. An ASPIRE study sheet satisfies the survey
requirement unchanged. See research/kbase/curation/r4/aspire_topology.md.

Stub: the model is the port, the body only touches its outputs.
Regenerate with `python transforms/aspire/_generate.py`.
"""

from metasmith.python_api import *

lib   = TransformInstanceLibrary.ResolveParentLibrary(__file__)
model = Transform()
survey = model.AddRequirement(lib.GetType("amplicon::survey"))
counts = model.AddRequirement(lib.GetType("amplicon::asv_table"), parents={survey})
md     = model.AddRequirement(lib.GetType("aspire::analysis_metadata"), parents={survey})
out    = model.AddProduct(lib.GetType("aspire::diversity_outputs"))

def protocol(context: ExecutionContext):
    made = {
        out: context.Output(out),
    }
    for key, path in made.items():
        make = 'mkdir -p' if key in _DIRECTORY_PRODUCTS else 'touch'
        context.external_shell.Exec(f'{make} {path.external}')
    return ExecutionResult(
        manifest=[{k: v.local for k, v in made.items()}],
        success=all(v.local.exists() for v in made.values()),
    )

_DIRECTORY_PRODUCTS = {out}

TransformInstance(
    protocol=protocol,
    model=model,
    group_by=survey,
    resources=Resources(
        cpus=4,
        memory=Size.GB(16),
        duration=Duration(hours=3),
    ),
)
