# generated by transforms/aspire/_generate.py -- do not hand-edit
"""fastp_qc -- FASTP_QC (asv_pipeline.nf:3121)

Reads `parity` from the read_metadata JSON: `--interleaved_in` for a paired
sample, plain `-i` for a single-end one. Settings under `fastp:` in the params
file. The product is an aspire type on purpose, so the shipped
kbase/clean_reads/fastp.py and bbduk cannot answer for this slot with their
own trimming.

Stub: the model is the port, the body only touches its outputs.
Regenerate with `python transforms/aspire/_generate.py`.
"""

from metasmith.python_api import *

lib   = TransformInstanceLibrary.ResolveParentLibrary(__file__)
model = Transform()
study  = model.AddRequirement(lib.GetType("aspire::study_metadata"))
meta   = model.AddRequirement(lib.GetType("sequences::read_metadata"), parents={study})
reads  = model.AddRequirement(lib.GetType("sequences::short_reads"), parents={meta})
params = model.AddRequirement(lib.GetType("aspire::params"), parents={study})
qc     = model.AddProduct(lib.GetType("aspire::qc_reads"))
rjson  = model.AddProduct(lib.GetType("aspire::fastp_report_json"))
rhtml  = model.AddProduct(lib.GetType("aspire::fastp_report_html"))

def protocol(context: ExecutionContext):
    made = {
        qc: context.Output(qc),
        rjson: context.Output(rjson),
        rhtml: context.Output(rhtml),
    }
    for key, path in made.items():
        make = 'mkdir -p' if key in _DIRECTORY_PRODUCTS else 'touch'
        context.external_shell.Exec(f'{make} {path.external}')
    return ExecutionResult(
        manifest=[{k: v.local for k, v in made.items()}],
        success=all(v.local.exists() for v in made.values()),
    )

_DIRECTORY_PRODUCTS = set()

TransformInstance(
    protocol=protocol,
    model=model,
    group_by=meta,
    resources=Resources(
        cpus=4,
        memory=Size.GB(4),
        duration=Duration(hours=2),
    ),
)
