# generated by transforms/aspire/_generate.py -- do not hand-edit
"""filter_table -- FILTER_TABLE (asv_pipeline.nf:3444)

Sample depth and ASV prevalence cuts, under `table_filter:`.

Stub: the model is the port, the body only touches its outputs.
Regenerate with `python transforms/aspire/_generate.py`.
"""

from metasmith.python_api import *

lib   = TransformInstanceLibrary.ResolveParentLibrary(__file__)
model = Transform()
study   = model.AddRequirement(lib.GetType("aspire::study_metadata"))
counts  = model.AddRequirement(lib.GetType("amplicon::asv_table"), parents={study})
seqs    = model.AddRequirement(lib.GetType("amplicon::asv_seqs"), parents={study})
params  = model.AddRequirement(lib.GetType("aspire::params"), parents={study})
fcounts = model.AddProduct(lib.GetType("aspire::asv_filtered_counts"))
fseqs   = model.AddProduct(lib.GetType("aspire::asv_filtered_seqs"))

def protocol(context: ExecutionContext):
    made = {
        fcounts: context.Output(fcounts),
        fseqs: context.Output(fseqs),
    }
    for key, path in made.items():
        make = 'mkdir -p' if key in _DIRECTORY_PRODUCTS else 'touch'
        context.external_shell.Exec(f'{make} {path.external}')
    return ExecutionResult(
        manifest=[{k: v.local for k, v in made.items()}],
        success=all(v.local.exists() for v in made.values()),
    )

_DIRECTORY_PRODUCTS = set()

TransformInstance(
    protocol=protocol,
    model=model,
    group_by=study,
    resources=Resources(
        cpus=1,
        memory=Size.GB(4),
        duration=Duration(hours=1),
    ),
)
