# generated by transforms/aspire/_generate.py -- do not hand-edit
"""graph_network_absent -- no .nf process

the `off` arm: an empty directory, which the master summary scans and finds
nothing in.

Stub: the model is the port, the body only touches its outputs.
Regenerate with `python transforms/aspire/_generate.py`.
"""

from metasmith.python_api import *

lib   = TransformInstanceLibrary.ResolveParentLibrary(__file__)
model = Transform()
survey = model.AddRequirement(lib.GetType("amplicon::survey"))
policy = model.AddRequirement(lib.GetType("aspire::graph_network_off"), parents={survey})
out    = model.AddProduct(lib.GetType("aspire::network_outputs"))

def protocol(context: ExecutionContext):
    made = {
        out: context.Output(out),
    }
    for key, path in made.items():
        make = 'mkdir -p' if key in _DIRECTORY_PRODUCTS else 'touch'
        context.external_shell.Exec(f'{make} {path.external}')
    return ExecutionResult(
        manifest=[{k: v.local for k, v in made.items()}],
        success=all(v.local.exists() for v in made.values()),
    )

_DIRECTORY_PRODUCTS = {out}

TransformInstance(
    protocol=protocol,
    model=model,
    group_by=survey,
    resources=Resources(
        cpus=1,
        memory=Size.GB(4),
        duration=Duration(hours=1),
    ),
)
