# generated by transforms/aspire/_generate.py -- do not hand-edit
"""graph_network -- GRAPH_NETWORK (asv_pipeline.nf:5579)

Hangs off the generic `amplicon::survey` grouping node and reads the curated
`amplicon::abundance_table`, so any analysis-ready count table reaches it --
`kbase/profile_abundance/kraken_abundance.py` makes one from kraken2 reports.
In an ASPIRE study the table is `plot_metadata`'s curated counts, never
`denoise`'s raw one: the raw table does not satisfy the requirement. See
research/kbase/curation/r4/aspire_topology.md. Reachable in principle and
expensive in practice: it renders a co-occurrence network, so running it
outside ASPIRE means supplying the network. That is a property of what it
does, not of the gate removed.

Stub: the model is the port, the body only touches its outputs.
Regenerate with `python transforms/aspire/_generate.py`.
"""

from metasmith.python_api import *

lib   = TransformInstanceLibrary.ResolveParentLibrary(__file__)
model = Transform()
survey  = model.AddRequirement(lib.GetType("amplicon::survey"))
policy  = model.AddRequirement(lib.GetType("aspire::graph_network_on"), parents={survey})
all     = model.AddRequirement(lib.GetType("aspire::network_graph_all"), parents={survey})
thr     = model.AddRequirement(lib.GetType("aspire::network_graph_thr"), parents={survey})
nf      = model.AddRequirement(lib.GetType("aspire::network_node_features"), parents={survey})
counts  = model.AddRequirement(lib.GetType("amplicon::abundance_table"), parents={survey})
md      = model.AddRequirement(lib.GetType("aspire::analysis_metadata"), parents={survey})
pairing = model.AddRequirement(lib.GetType("aspire::asv_mag_pairing"), parents={survey})
tax     = model.AddRequirement(lib.GetType("amplicon::asv_taxonomy"), parents={survey})
tables  = model.AddRequirement(lib.GetType("aspire::indicspecies_tables"), parents={survey})
sub     = model.AddRequirement(lib.GetType("aspire::network_modules_sub"), parents={survey})
mall    = model.AddRequirement(lib.GetType("aspire::network_modules_all"), parents={survey})
out     = model.AddProduct(lib.GetType("aspire::network_outputs"))

def protocol(context: ExecutionContext):
    made = {
        out: context.Output(out),
    }
    for key, path in made.items():
        make = 'mkdir -p' if key in _DIRECTORY_PRODUCTS else 'touch'
        context.external_shell.Exec(f'{make} {path.external}')
    return ExecutionResult(
        manifest=[{k: v.local for k, v in made.items()}],
        success=all(v.local.exists() for v in made.values()),
    )

_DIRECTORY_PRODUCTS = {out}

TransformInstance(
    protocol=protocol,
    model=model,
    group_by=survey,
    resources=Resources(
        cpus=8,
        memory=Size.GB(32),
        duration=Duration(hours=6),
    ),
)
