# generated by transforms/aspire/_generate.py -- do not hand-edit
"""master_summary -- MASTER_SUMMARY (asv_pipeline.nf:5763)

The script scans four directories for the tables in its whitelist:
clustermaps, indicator species, the network's (node features and modules,
which `graph_network` copies into its outputs) and the link's. Each is
declared, plus the anchor table the .nf wrote into the network directory. The
sankey barrier is dropped: the script reads nothing of the sankey's. Which
tables merge stays a runtime whitelist, defaulted to this port's file names.

Stub: the model is the port, the body only touches its outputs.
Regenerate with `python transforms/aspire/_generate.py`.
"""

from metasmith.python_api import *

lib   = TransformInstanceLibrary.ResolveParentLibrary(__file__)
model = Transform()
study      = model.AddRequirement(lib.GetType("aspire::study_metadata"))
am         = model.AddRequirement(lib.GetType("aspire::analysis_asv_meta"), parents={study})
counts     = model.AddRequirement(lib.GetType("aspire::analysis_counts"), parents={study})
cmaps      = model.AddRequirement(lib.GetType("aspire::clustermap_outputs"), parents={study})
indic      = model.AddRequirement(lib.GetType("aspire::indicspecies_results"), parents={study})
net        = model.AddRequirement(lib.GetType("aspire::network_outputs"), parents={study})
anchors    = model.AddRequirement(lib.GetType("aspire::module_asv_anchor_table"), parents={study})
magl       = model.AddRequirement(lib.GetType("aspire::asv_mag_outputs"), parents={study})
long       = model.AddProduct(lib.GetType("aspire::master_long"))
wide       = model.AddProduct(lib.GetType("aspire::master_count_wide"))
manifest   = model.AddProduct(lib.GetType("aspire::master_source_manifest"))
colmap     = model.AddProduct(lib.GetType("aspire::master_column_mapping"))
collisions = model.AddProduct(lib.GetType("aspire::master_column_collisions"))

def protocol(context: ExecutionContext):
    made = {
        long: context.Output(long),
        wide: context.Output(wide),
        manifest: context.Output(manifest),
        colmap: context.Output(colmap),
        collisions: context.Output(collisions),
    }
    for key, path in made.items():
        make = 'mkdir -p' if key in _DIRECTORY_PRODUCTS else 'touch'
        context.external_shell.Exec(f'{make} {path.external}')
    return ExecutionResult(
        manifest=[{k: v.local for k, v in made.items()}],
        success=all(v.local.exists() for v in made.values()),
    )

_DIRECTORY_PRODUCTS = set()

TransformInstance(
    protocol=protocol,
    model=model,
    group_by=study,
    resources=Resources(
        cpus=4,
        memory=Size.GB(32),
        duration=Duration(hours=4),
    ),
)
