# generated by transforms/aspire/_generate.py -- do not hand-edit
"""measurement_association -- MEASUREMENT_ASSOCIATION (asv_pipeline.nf:4875)

Hangs off the generic `amplicon::survey` grouping node and reads the curated
`amplicon::abundance_table`, so any analysis-ready count table reaches it --
`kbase/profile_abundance/kraken_abundance.py` makes one from kraken2 reports.
In an ASPIRE study the table is `plot_metadata`'s curated counts, never
`denoise`'s raw one: the raw table does not satisfy the requirement. See
research/kbase/curation/r4/aspire_topology.md.

Stub: the model is the port, the body only touches its outputs.
Regenerate with `python transforms/aspire/_generate.py`.
"""

from metasmith.python_api import *

lib   = TransformInstanceLibrary.ResolveParentLibrary(__file__)
model = Transform()
survey   = model.AddRequirement(lib.GetType("amplicon::survey"))
counts   = model.AddRequirement(lib.GetType("amplicon::abundance_table"), parents={survey})
am       = model.AddRequirement(lib.GetType("aspire::analysis_asv_meta"), parents={survey})
md       = model.AddRequirement(lib.GetType("aspire::analysis_metadata"), parents={survey})
measures = model.AddRequirement(lib.GetType("aspire::sample_measurements"), parents={survey})
out      = model.AddProduct(lib.GetType("aspire::measurement_association_outputs"))

def protocol(context: ExecutionContext):
    made = {
        out: context.Output(out),
    }
    for key, path in made.items():
        make = 'mkdir -p' if key in _DIRECTORY_PRODUCTS else 'touch'
        context.external_shell.Exec(f'{make} {path.external}')
    return ExecutionResult(
        manifest=[{k: v.local for k, v in made.items()}],
        success=all(v.local.exists() for v in made.values()),
    )

_DIRECTORY_PRODUCTS = {out}

TransformInstance(
    protocol=protocol,
    model=model,
    group_by=survey,
    resources=Resources(
        cpus=2,
        memory=Size.GB(8),
        duration=Duration(hours=1),
    ),
)
