# generated by transforms/aspire/_generate.py -- do not hand-edit
"""merge_and_filter_reads -- FILTER_READS (asv_pipeline.nf:3221)

Folded in: MERGE_READS (asv_pipeline.nf:3179)

Branches on `parity`. Paired: `vsearch --fastq_mergepairs` (settings under
`merge:`) then `--fastq_filter` (under `filter:`). Single-end: the filter
alone. The merged pair is not a product; what a reader wants from the merge is
its rate, which goes in the per-sample count file beside the filtered reads
for read_accounting.

Stub: the model is the port, the body only touches its outputs.
Regenerate with `python transforms/aspire/_generate.py`.
"""

from metasmith.python_api import *

lib   = TransformInstanceLibrary.ResolveParentLibrary(__file__)
model = Transform()
study    = model.AddRequirement(lib.GetType("aspire::study_metadata"))
meta     = model.AddRequirement(lib.GetType("sequences::read_metadata"), parents={study})
qc       = model.AddRequirement(lib.GetType("aspire::qc_reads"), parents={meta})
params   = model.AddRequirement(lib.GetType("aspire::params"), parents={study})
filtered = model.AddProduct(lib.GetType("aspire::filtered_fasta"))
counts   = model.AddProduct(lib.GetType("aspire::read_counts"))

def protocol(context: ExecutionContext):
    made = {
        filtered: context.Output(filtered),
        counts: context.Output(counts),
    }
    for key, path in made.items():
        make = 'mkdir -p' if key in _DIRECTORY_PRODUCTS else 'touch'
        context.external_shell.Exec(f'{make} {path.external}')
    return ExecutionResult(
        manifest=[{k: v.local for k, v in made.items()}],
        success=all(v.local.exists() for v in made.values()),
    )

_DIRECTORY_PRODUCTS = set()

TransformInstance(
    protocol=protocol,
    model=model,
    group_by=meta,
    resources=Resources(
        cpus=4,
        memory=Size.GB(4),
        duration=Duration(hours=2),
    ),
)
