# generated by transforms/aspire/_generate.py -- do not hand-edit
"""mitomaster -- MITOMASTER (asv_pipeline.nf:3544)

Folded in: PREPARE_BLAST_DATABASES (asv_pipeline.nf:3511)

r4 fold. PREPARE_BLAST_DATABASES was two makeblastdb calls whose products each
had one consumer, which was this transform. The standard library already
treats that as inside-the-transform work -- amplicon/blast_map_asvs.py runs
makeblastdb and then blastn in one protocol -- so the two reference FASTAs
move up here.

Stub: the model is the port, the body only touches its outputs.
Regenerate with `python transforms/aspire/_generate.py`.
"""

from metasmith.python_api import *

lib   = TransformInstanceLibrary.ResolveParentLibrary(__file__)
model = Transform()
study    = model.AddRequirement(lib.GetType("aspire::study_metadata"))
fcounts  = model.AddRequirement(lib.GetType("aspire::asv_filtered_counts"), parents={study})
fseqs    = model.AddRequirement(lib.GetType("aspire::asv_filtered_seqs"), parents={study})
mito_src = model.AddRequirement(lib.GetType("aspire::mito_reference_source"))
cont_src = model.AddRequirement(lib.GetType("aspire::contaminant_reference_source"))
master   = model.AddProduct(lib.GetType("aspire::mitomaster_table"))
mhits    = model.AddProduct(lib.GetType("aspire::mito_blast6"))
chits    = model.AddProduct(lib.GetType("aspire::contaminant_blast6"))

def protocol(context: ExecutionContext):
    made = {
        master: context.Output(master),
        mhits: context.Output(mhits),
        chits: context.Output(chits),
    }
    for key, path in made.items():
        make = 'mkdir -p' if key in _DIRECTORY_PRODUCTS else 'touch'
        context.external_shell.Exec(f'{make} {path.external}')
    return ExecutionResult(
        manifest=[{k: v.local for k, v in made.items()}],
        success=all(v.local.exists() for v in made.values()),
    )

_DIRECTORY_PRODUCTS = set()

TransformInstance(
    protocol=protocol,
    model=model,
    group_by=study,
    resources=Resources(
        cpus=8,
        memory=Size.GB(16),
        duration=Duration(hours=6),
    ),
)
