# generated by transforms/aspire/_generate.py -- do not hand-edit
"""module_mag_anchors_absent -- no .nf process

the `off` arm: a header-only anchor table, so the master summary solves
without a link.

Stub: the model is the port, the body only touches its outputs.
Regenerate with `python transforms/aspire/_generate.py`.
"""

from metasmith.python_api import *

lib   = TransformInstanceLibrary.ResolveParentLibrary(__file__)
model = Transform()
study   = model.AddRequirement(lib.GetType("aspire::study_metadata"))
policy  = model.AddRequirement(lib.GetType("aspire::asv_mag_link_off"), parents={study})
anchors = model.AddProduct(lib.GetType("aspire::module_asv_anchor_table"))

def protocol(context: ExecutionContext):
    made = {
        anchors: context.Output(anchors),
    }
    for key, path in made.items():
        make = 'mkdir -p' if key in _DIRECTORY_PRODUCTS else 'touch'
        context.external_shell.Exec(f'{make} {path.external}')
    return ExecutionResult(
        manifest=[{k: v.local for k, v in made.items()}],
        success=all(v.local.exists() for v in made.values()),
    )

_DIRECTORY_PRODUCTS = set()

TransformInstance(
    protocol=protocol,
    model=model,
    group_by=study,
    resources=Resources(
        cpus=1,
        memory=Size.GB(4),
        duration=Duration(hours=1),
    ),
)
