# generated by transforms/aspire/_generate.py -- do not hand-edit
"""network_modules -- NETWORK_MODULES (asv_pipeline.nf:5522)

r4 ecology lift (second pass): lifted off the study root onto the generic
`amplicon::survey` grouping node so `spieceasi` and `graph_network` -- lifted
in the first pass -- are actually REACHABLE from a bare `amplicon::asv_table`.
Lifting a transform whose own inputs are still gated moves the gate, it does
not remove it. See research/kbase/curation/r4/analyses.md.

Stub: the model is the port, the body only touches its outputs.
Regenerate with `python transforms/aspire/_generate.py`.
"""

from metasmith.python_api import *

lib   = TransformInstanceLibrary.ResolveParentLibrary(__file__)
model = Transform()
survey  = model.AddRequirement(lib.GetType("amplicon::survey"))
policy  = model.AddRequirement(lib.GetType("aspire::network_modules_on"), parents={survey})
all     = model.AddRequirement(lib.GetType("aspire::network_graph_all"), parents={survey})
thr     = model.AddRequirement(lib.GetType("aspire::network_graph_thr"), parents={survey})
sub     = model.AddProduct(lib.GetType("aspire::network_modules_sub"))
mall    = model.AddProduct(lib.GetType("aspire::network_modules_all"))
summary = model.AddProduct(lib.GetType("aspire::network_modules_summary"))
runs    = model.AddProduct(lib.GetType("aspire::network_modules_runs"))

def protocol(context: ExecutionContext):
    made = {
        sub: context.Output(sub),
        mall: context.Output(mall),
        summary: context.Output(summary),
        runs: context.Output(runs),
    }
    for key, path in made.items():
        make = 'mkdir -p' if key in _DIRECTORY_PRODUCTS else 'touch'
        context.external_shell.Exec(f'{make} {path.external}')
    return ExecutionResult(
        manifest=[{k: v.local for k, v in made.items()}],
        success=all(v.local.exists() for v in made.values()),
    )

_DIRECTORY_PRODUCTS = set()

TransformInstance(
    protocol=protocol,
    model=model,
    group_by=survey,
    resources=Resources(
        cpus=8,
        memory=Size.GB(32),
        duration=Duration(hours=6),
    ),
)
