# generated by transforms/aspire/_generate.py -- do not hand-edit
"""network_modules_absent -- no .nf process

r4 ecology lift (second pass): lifted off the study root onto the generic
`amplicon::survey` grouping node so `spieceasi` and `graph_network` -- lifted
in the first pass -- are actually REACHABLE from a bare `amplicon::asv_table`.
Lifting a transform whose own inputs are still gated moves the gate, it does
not remove it. See research/kbase/curation/r4/analyses.md. the `off` arm;
asv_pipeline.nf:2726-2729 falls back to files on disk if they exist and a
zero-row placeholder if not.

Stub: the model is the port, the body only touches its outputs.
Regenerate with `python transforms/aspire/_generate.py`.
"""

from metasmith.python_api import *

lib   = TransformInstanceLibrary.ResolveParentLibrary(__file__)
model = Transform()
survey = model.AddRequirement(lib.GetType("amplicon::survey"))
policy = model.AddRequirement(lib.GetType("aspire::network_modules_off"), parents={survey})
sub    = model.AddProduct(lib.GetType("aspire::network_modules_sub"))
mall   = model.AddProduct(lib.GetType("aspire::network_modules_all"))

def protocol(context: ExecutionContext):
    made = {
        sub: context.Output(sub),
        mall: context.Output(mall),
    }
    for key, path in made.items():
        make = 'mkdir -p' if key in _DIRECTORY_PRODUCTS else 'touch'
        context.external_shell.Exec(f'{make} {path.external}')
    return ExecutionResult(
        manifest=[{k: v.local for k, v in made.items()}],
        success=all(v.local.exists() for v in made.values()),
    )

_DIRECTORY_PRODUCTS = set()

TransformInstance(
    protocol=protocol,
    model=model,
    group_by=survey,
    resources=Resources(
        cpus=1,
        memory=Size.GB(4),
        duration=Duration(hours=1),
    ),
)
