# generated by transforms/aspire/_generate.py -- do not hand-edit
"""outlier_checker -- OUTLIER_CHECKER (asv_pipeline.nf:4316)

reads the CLR matrix, which only the correction arm produces -- so this stage
needs batch correction on, exactly as in the .nf, without a token of its own.

Stub: the model is the port, the body only touches its outputs.
Regenerate with `python transforms/aspire/_generate.py`.
"""

from metasmith.python_api import *

lib   = TransformInstanceLibrary.ResolveParentLibrary(__file__)
model = Transform()
run = model.AddRequirement(lib.GetType("aspire::run"))
clr = model.AddRequirement(lib.GetType("aspire::asv_clr_after"), parents={run})
md  = model.AddRequirement(lib.GetType("aspire::analysis_metadata"), parents={run})
out = model.AddProduct(lib.GetType("aspire::outlier_outputs"))

def protocol(context: ExecutionContext):
    made = {
        out: context.Output(out),
    }
    for key, path in made.items():
        make = 'mkdir -p' if key in _DIRECTORY_PRODUCTS else 'touch'
        context.external_shell.Exec(f'{make} {path.external}')
    return ExecutionResult(
        manifest=[{k: v.local for k, v in made.items()}],
        success=all(v.local.exists() for v in made.values()),
    )

_DIRECTORY_PRODUCTS = {out}

TransformInstance(
    protocol=protocol,
    model=model,
    group_by=run,
    resources=Resources(
        cpus=1,
        memory=Size.GB(4),
        duration=Duration(hours=1),
    ),
)
