# generated by transforms/aspire/_generate.py -- do not hand-edit
"""plot_upset -- PLOT_UPSET (asv_pipeline.nf:3927)

Groups are the label columns of the sample sheet; the analysis runs once per
label and skips a label with fewer than two levels.

Stub: the model is the port, the body only touches its outputs.
Regenerate with `python transforms/aspire/_generate.py`.
"""

from metasmith.python_api import *

lib   = TransformInstanceLibrary.ResolveParentLibrary(__file__)
model = Transform()
study = model.AddRequirement(lib.GetType("aspire::study_metadata"))
md    = model.AddRequirement(lib.GetType("aspire::analysis_metadata"), parents={study})
out   = model.AddProduct(lib.GetType("aspire::upset_plots"))

def protocol(context: ExecutionContext):
    made = {
        out: context.Output(out),
    }
    for key, path in made.items():
        make = 'mkdir -p' if key in _DIRECTORY_PRODUCTS else 'touch'
        context.external_shell.Exec(f'{make} {path.external}')
    return ExecutionResult(
        manifest=[{k: v.local for k, v in made.items()}],
        success=all(v.local.exists() for v in made.values()),
    )

_DIRECTORY_PRODUCTS = {out}

TransformInstance(
    protocol=protocol,
    model=model,
    group_by=study,
    resources=Resources(
        cpus=1,
        memory=Size.GB(4),
        duration=Duration(hours=1),
    ),
)
