# generated by transforms/aspire/_generate.py -- do not hand-edit
"""plot_metadata -- PLOT_METADATA (asv_pipeline.nf:3793)

the join that turns counts into an analysis table. Everything downstream of
here reads one of the three consumer-facing channels, not these directly.

Stub: the model is the port, the body only touches its outputs.
Regenerate with `python transforms/aspire/_generate.py`.
"""

from metasmith.python_api import *

lib   = TransformInstanceLibrary.ResolveParentLibrary(__file__)
model = Transform()
run      = model.AddRequirement(lib.GetType("aspire::run"))
fastq    = model.AddRequirement(lib.GetType("aspire::fastq_stats"), parents={run})
micro    = model.AddRequirement(lib.GetType("aspire::counts_filtered"), parents={run})
mito     = model.AddRequirement(lib.GetType("aspire::counts_mito"), parents={run})
tax      = model.AddRequirement(lib.GetType("amplicon::asv_taxonomy"), parents={run})
meta     = model.AddRequirement(lib.GetType("aspire::sample_metadata"))
md_micro = model.AddProduct(lib.GetType("aspire::metadata_micro"))
am_micro = model.AddProduct(lib.GetType("aspire::asv_meta_micro"))
af_micro = model.AddProduct(lib.GetType("aspire::asv_final_micro"))
md_mito  = model.AddProduct(lib.GetType("aspire::metadata_mito"))
am_mito  = model.AddProduct(lib.GetType("aspire::asv_meta_mito"))
af_mito  = model.AddProduct(lib.GetType("aspire::asv_final_mito"))

def protocol(context: ExecutionContext):
    made = {
        md_micro: context.Output(md_micro),
        am_micro: context.Output(am_micro),
        af_micro: context.Output(af_micro),
        md_mito: context.Output(md_mito),
        am_mito: context.Output(am_mito),
        af_mito: context.Output(af_mito),
    }
    for key, path in made.items():
        make = 'mkdir -p' if key in _DIRECTORY_PRODUCTS else 'touch'
        context.external_shell.Exec(f'{make} {path.external}')
    return ExecutionResult(
        manifest=[{k: v.local for k, v in made.items()}],
        success=all(v.local.exists() for v in made.values()),
    )

_DIRECTORY_PRODUCTS = set()

TransformInstance(
    protocol=protocol,
    model=model,
    group_by=run,
    resources=Resources(
        cpus=4,
        memory=Size.GB(16),
        duration=Duration(hours=3),
    ),
)
