# generated by transforms/aspire/_generate.py -- do not hand-edit
"""plot_metadata -- PLOT_METADATA (asv_pipeline.nf:3793)

The join that turns counts into analysis tables, and now the only producer of
the three consumer-facing channels. The .nf rebound those channels through
label augmentation and batch correction; both are off by default, outside the
reads-to-ASV pipeline, and not ported. The mitochondrial tables come from the
removed counts whose reason is mitochondrial. A label value held by fewer than
`analysis.min_level_size` samples is blanked here, so every analysis skips
that level and keeps the sample.

Stub: the model is the port, the body only touches its outputs.
Regenerate with `python transforms/aspire/_generate.py`.
"""

from metasmith.python_api import *

lib   = TransformInstanceLibrary.ResolveParentLibrary(__file__)
model = Transform()
study   = model.AddRequirement(lib.GetType("aspire::study_metadata"))
fate    = model.AddRequirement(lib.GetType("aspire::read_fate"), parents={study})
clean   = model.AddRequirement(lib.GetType("aspire::counts_clean"), parents={study})
removed = model.AddRequirement(lib.GetType("aspire::counts_removed"), parents={study})
tax     = model.AddRequirement(lib.GetType("amplicon::asv_taxonomy"), parents={study})
params  = model.AddRequirement(lib.GetType("aspire::params"), parents={study})
md      = model.AddProduct(lib.GetType("aspire::analysis_metadata"))
am      = model.AddProduct(lib.GetType("aspire::analysis_asv_meta"))
counts  = model.AddProduct(lib.GetType("aspire::analysis_counts"))
md_mito = model.AddProduct(lib.GetType("aspire::metadata_mito"))
am_mito = model.AddProduct(lib.GetType("aspire::asv_meta_mito"))
af_mito = model.AddProduct(lib.GetType("aspire::asv_final_mito"))

def protocol(context: ExecutionContext):
    made = {
        md: context.Output(md),
        am: context.Output(am),
        counts: context.Output(counts),
        md_mito: context.Output(md_mito),
        am_mito: context.Output(am_mito),
        af_mito: context.Output(af_mito),
    }
    for key, path in made.items():
        make = 'mkdir -p' if key in _DIRECTORY_PRODUCTS else 'touch'
        context.external_shell.Exec(f'{make} {path.external}')
    return ExecutionResult(
        manifest=[{k: v.local for k, v in made.items()}],
        success=all(v.local.exists() for v in made.values()),
    )

_DIRECTORY_PRODUCTS = set()

TransformInstance(
    protocol=protocol,
    model=model,
    group_by=study,
    resources=Resources(
        cpus=4,
        memory=Size.GB(16),
        duration=Duration(hours=3),
    ),
)
