# generated by transforms/aspire/_generate.py -- do not hand-edit
"""read_accounting -- GENERAL_STATS (asv_pipeline.nf:3755)

One row per sample, one column per stage: raw and post-fastp from the fastp
report, merged and filtered from the per-sample count file, mapped from the
ASV table, then kept and removed by reason. The .nf read these out of other
processes' publish directories behind an ordering barrier; every one is now a
declared input.

Stub: the model is the port, the body only touches its outputs.
Regenerate with `python transforms/aspire/_generate.py`.
"""

from metasmith.python_api import *

lib   = TransformInstanceLibrary.ResolveParentLibrary(__file__)
model = Transform()
run     = model.AddRequirement(lib.GetType("aspire::run"))
name    = model.AddRequirement(lib.GetType("sequences::sample_name"), parents={run})
rjson   = model.AddRequirement(lib.GetType("aspire::fastp_report_json"), parents={name})
rcounts = model.AddRequirement(lib.GetType("aspire::read_counts"), parents={name})
raw     = model.AddRequirement(lib.GetType("amplicon::asv_table"), parents={run})
clean   = model.AddRequirement(lib.GetType("aspire::counts_clean"), parents={run})
removed = model.AddRequirement(lib.GetType("aspire::counts_removed"), parents={run})
fate    = model.AddProduct(lib.GetType("aspire::read_fate"))

def protocol(context: ExecutionContext):
    made = {
        fate: context.Output(fate),
    }
    for key, path in made.items():
        make = 'mkdir -p' if key in _DIRECTORY_PRODUCTS else 'touch'
        context.external_shell.Exec(f'{make} {path.external}')
    return ExecutionResult(
        manifest=[{k: v.local for k, v in made.items()}],
        success=all(v.local.exists() for v in made.values()),
    )

_DIRECTORY_PRODUCTS = set()

TransformInstance(
    protocol=protocol,
    model=model,
    group_by=run,
    resources=Resources(
        cpus=1,
        memory=Size.GB(4),
        duration=Duration(hours=1),
    ),
)
