# generated by transforms/aspire/_generate.py -- do not hand-edit
"""sankey -- SANKEY (asv_pipeline.nf:3687)

`sankey.done` is dropped; the renderings are the output, and MASTER_SUMMARY
reads the directory rather than the sentinel.

Stub: the model is the port, the body only touches its outputs.
Regenerate with `python transforms/aspire/_generate.py`.
"""

from metasmith.python_api import *

lib   = TransformInstanceLibrary.ResolveParentLibrary(__file__)
model = Transform()
run      = model.AddRequirement(lib.GetType("aspire::run"))
policy   = model.AddRequirement(lib.GetType("aspire::sankey_on"), parents={run})
fastq    = model.AddRequirement(lib.GetType("aspire::fastq_stats"), parents={run})
filtered = model.AddRequirement(lib.GetType("aspire::filtered_stats"), parents={run})
raw      = model.AddRequirement(lib.GetType("amplicon::asv_table"), parents={run})
decon    = model.AddRequirement(lib.GetType("aspire::counts_decon"), parents={run})
micro    = model.AddRequirement(lib.GetType("aspire::counts_micro"), parents={run})
meta     = model.AddRequirement(lib.GetType("aspire::sample_metadata"))
out      = model.AddProduct(lib.GetType("aspire::sankey_outputs"))

def protocol(context: ExecutionContext):
    made = {
        out: context.Output(out),
    }
    for key, path in made.items():
        make = 'mkdir -p' if key in _DIRECTORY_PRODUCTS else 'touch'
        context.external_shell.Exec(f'{make} {path.external}')
    return ExecutionResult(
        manifest=[{k: v.local for k, v in made.items()}],
        success=all(v.local.exists() for v in made.values()),
    )

_DIRECTORY_PRODUCTS = {out}

TransformInstance(
    protocol=protocol,
    model=model,
    group_by=run,
    resources=Resources(
        cpus=1,
        memory=Size.GB(4),
        duration=Duration(hours=1),
    ),
)
