# generated by transforms/aspire/_generate.py -- do not hand-edit
"""sankey -- SANKEY (asv_pipeline.nf:3687)

`sankey.done` is dropped; the renderings are the output, and MASTER_SUMMARY
reads the directory rather than the sentinel.

Stub: the model is the port, the body only touches its outputs.
Regenerate with `python transforms/aspire/_generate.py`.
"""

from metasmith.python_api import *

lib   = TransformInstanceLibrary.ResolveParentLibrary(__file__)
model = Transform()
study   = model.AddRequirement(lib.GetType("aspire::study_metadata"))
fate    = model.AddRequirement(lib.GetType("aspire::read_fate"), parents={study})
removed = model.AddRequirement(lib.GetType("aspire::counts_removed"), parents={study})
out     = model.AddProduct(lib.GetType("aspire::sankey_outputs"))

def protocol(context: ExecutionContext):
    made = {
        out: context.Output(out),
    }
    for key, path in made.items():
        make = 'mkdir -p' if key in _DIRECTORY_PRODUCTS else 'touch'
        context.external_shell.Exec(f'{make} {path.external}')
    return ExecutionResult(
        manifest=[{k: v.local for k, v in made.items()}],
        success=all(v.local.exists() for v in made.values()),
    )

_DIRECTORY_PRODUCTS = {out}

TransformInstance(
    protocol=protocol,
    model=model,
    group_by=study,
    resources=Resources(
        cpus=1,
        memory=Size.GB(4),
        duration=Duration(hours=1),
    ),
)
