# generated by transforms/aspire/_generate.py -- do not hand-edit
"""spieceasi -- SPIECEASI (asv_pipeline.nf:5452)

Force-keeps every ASV the indicator species results call significant for any
label. r4 ecology lift: requires the generic `amplicon::survey` grouping node
and a bare `amplicon::asv_table` instead of the study root and
`aspire::analysis_counts`, so it is reachable from any count table --
`kbase/profile_abundance/kraken_abundance.py` produces one from kraken2
reports. An ASPIRE study sheet satisfies the survey requirement unchanged. See
research/kbase/curation/r4/aspire_topology.md.

Stub: the model is the port, the body only touches its outputs.
Regenerate with `python transforms/aspire/_generate.py`.
"""

from metasmith.python_api import *

lib   = TransformInstanceLibrary.ResolveParentLibrary(__file__)
model = Transform()
survey = model.AddRequirement(lib.GetType("amplicon::survey"))
policy = model.AddRequirement(lib.GetType("aspire::spieceasi_on"), parents={survey})
counts = model.AddRequirement(lib.GetType("amplicon::asv_table"), parents={survey})
keep   = model.AddRequirement(lib.GetType("aspire::indicspecies_results"), parents={survey})
all    = model.AddProduct(lib.GetType("aspire::network_graph_all"))
thr    = model.AddProduct(lib.GetType("aspire::network_graph_thr"))
nf     = model.AddProduct(lib.GetType("aspire::network_node_features"))

def protocol(context: ExecutionContext):
    made = {
        all: context.Output(all),
        thr: context.Output(thr),
        nf: context.Output(nf),
    }
    for key, path in made.items():
        make = 'mkdir -p' if key in _DIRECTORY_PRODUCTS else 'touch'
        context.external_shell.Exec(f'{make} {path.external}')
    return ExecutionResult(
        manifest=[{k: v.local for k, v in made.items()}],
        success=all(v.local.exists() for v in made.values()),
    )

_DIRECTORY_PRODUCTS = set()

TransformInstance(
    protocol=protocol,
    model=model,
    group_by=survey,
    resources=Resources(
        cpus=16,
        memory=Size.GB(64),
        duration=Duration(hours=24),
    ),
)
