# generated by transforms/aspire/_generate.py -- do not hand-edit
"""taxonomy -- TAXONOMY (asv_pipeline.nf:3470)

Absorbs the retired placeholder lane's amplicon/qiime2_taxonomy.py. Its
method, for the protocol pass: `qiime feature-classifier classify-sklearn`
with the NB classifier, then `classify-consensus-vsearch` against the SILVA
sequences and taxonomy (perc-identity 0.70, min-consensus 0.51, maxaccepts 10,
maxrejects 10), and a merge that keeps the NB call unless it is Unassigned or
Unclassified, falls back to the vsearch call, and records which one won.
Columns: Feature ID, Taxon, Confidence, Source. That file fetched SILVA 138-99
with wget inside the protocol; here the classifier, sequences and taxonomy
come from the one `amplicon::silva_db` bundle, as SINA's ARB file does.

Stub: the model is the port, the body only touches its outputs.
Regenerate with `python transforms/aspire/_generate.py`.
"""

from metasmith.python_api import *

lib   = TransformInstanceLibrary.ResolveParentLibrary(__file__)
model = Transform()
study   = model.AddRequirement(lib.GetType("aspire::study_metadata"))
trimmed = model.AddRequirement(lib.GetType("aspire::sina_trimmed_seqs"), parents={study})
silva   = model.AddRequirement(lib.GetType("amplicon::silva_db"))
tax     = model.AddProduct(lib.GetType("amplicon::asv_taxonomy"))
upper   = model.AddProduct(lib.GetType("aspire::taxonomy_uppercase_seqs"))
stats   = model.AddProduct(lib.GetType("aspire::taxonomy_stats"))

def protocol(context: ExecutionContext):
    made = {
        tax: context.Output(tax),
        upper: context.Output(upper),
        stats: context.Output(stats),
    }
    for key, path in made.items():
        make = 'mkdir -p' if key in _DIRECTORY_PRODUCTS else 'touch'
        context.external_shell.Exec(f'{make} {path.external}')
    return ExecutionResult(
        manifest=[{k: v.local for k, v in made.items()}],
        success=all(v.local.exists() for v in made.values()),
    )

_DIRECTORY_PRODUCTS = set()

TransformInstance(
    protocol=protocol,
    model=model,
    group_by=study,
    resources=Resources(
        cpus=8,
        memory=Size.GB(16),
        duration=Duration(hours=6),
    ),
)
